### ISSUE TITLE
Customizing disk_led.sls in DeepSea

### ISSUE THREAD

**Issue by votdev** [SUSE/doc-ses#286]
**Link To Section**
Please provide a link to the section or chapter you are reporting this bug for.

http://docserv.suse.de/documents/SES_6/ses-admin/html/storage-tips.html#id-1.3.8.2.14.7

**Summary**

The documentation is suggesting to override a file that is shipped by the installation package, because of that all changes will get lost after an update.

**Steps To Reproduce**
Steps to reproduce the behavior.

**Expected Results**

The documentation should explain that it is possible to customize the default behavior of the disk_led.sls by using the DeepSea way (https://github.com/SUSE/DeepSea/blob/master/srv/pillar/ceph/README).

This is done for example here: http://docserv.suse.de/documents/SES_6/ses-admin/html/storage-troubleshooting.html#storage-bp-recover-clockskew

**Actual Results**
Explain what actually happened when the steps were executed, and if applicable, add screenshots to help explain your problem.

**Notes**

The documentation should mention this:

The default behavior can be customized by adding e.g. for the ledmon package and ledctl tool.
``` 
disk_led:
  cmd:
    ident:
      'on': ledctl locate='{device_file}'
      'off': ledctl locate_off='{device_file}'
    fault:
      'on': ledctl locate='{device_file}'
      'off': ledctl locate_off='{device_file}'
```
to `/srv/pillar/ceph/stack/global.yml` or any other YAML file mentioned in https://github.com/SUSE/DeepSea/blob/master/srv/pillar/ceph/README. If the customization should only apply to a special node (minion), then the file `stack/ceph/minions/{{minion}}.yml` needs to be used. Simply reference to the section where this DeepSea feature is explained.
