### ISSUE TITLE
[doc] 6.5.3.5  Deploy NFS Ganesha (indentation)

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#379]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.5  Deploy NFS Ganesha:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-nfs

### Summary

There is a mistake in the NFS service spec:

```
service_type: nfs
service_id: EXAMPLE_NFS
placement:
 hosts:
  - ses-min1
  - ses-min2
 spec:
 pool: EXAMPLE_POOL
 namespace: EXAMPLE_NAMESPACE
```

Instead of the above, it should look like this:

```
service_type: nfs
service_id: EXAMPLE_NFS
placement:
    hosts:
        - ses-min1
        - ses-min2
spec:
    pool: EXAMPLE_POOL
    namespace: EXAMPLE_NAMESPACE
```

(Indentation is not clear)
