### ISSUE TITLE
[doc] 6.5.2.3  Applying Cluster Specification - structure for mon and mgr in one cluster.yaml?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#384]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.2.3  Applying Cluster Specification:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#cephadm-appply-cluster-specs

### Summary
With MON and MGR in one cluster.yaml only the MGRs get deployed

### Steps To Reproduce
I tried to follow this and created a cluster.yaml this way:

```
service_type: mon
placement:
 hosts:
  - ses7-01
  - ses7-02
  - ses7-03
service_type: mgr
placement:
 hosts:
  - ses7-01
  - ses7-02
  - ses7-03
```

Then I  applied this with `ceph orch apply -i cluster.yaml`

### Expected Results
Expectation was to get three MGR and three MONs

### Actual Results
Just had 1 MON but three MGR

### Notes
My workaround was then to create two yaml files: 
mon.yaml and mgr.yaml which had only one of them and then I applied them separately.

So question is how can we configure a single cluster.yaml with all services included - or is the concept to have one per component?

**Comment by lezare** [comment]
I think that indeed can not work, because we have multiple "service_type:" tags in the file it results in a (silent?) yml syntax error and only the last service block will get executed, which is why you only got the mgrs deployed. Since I am no expert at yml, maybe there is a way to properly specify this all in one file, else we will need to get the documentation updated to not state:

"After you have created a full cluster.yml file with specifications of all services and their placement, you can apply the cluster by running the following command ..."

If it is somehow possible however, we need to get a more detailed example in the documentation showing how to properly specify multiple services in one yml file.

**Comment by Martin-Weiss** [comment]
At least we have to properly document if single yaml files need to be used or if multiple ones need to be used.
(I hope we can have a merged one - but then we need to know if i.e. --- is required or some further intentions are required etc..)

**Comment by sebastian-philipp** [comment]
```yaml
service_type: mon
placement:
 hosts:
  - ses7-01
  - ses7-02
  - ses7-03
---
service_type: mgr
placement:
 hosts:
  - ses7-01
  - ses7-02
  - ses7-03
```

as described in https://ceph.readthedocs.io/en/latest/mgr/orchestrator/#service-specification should work
