### ISSUE TITLE
[doc] 6.5.3.4  Deploy Object Gateways

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#390]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.4  Deploy Object Gateways:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-ogw

### Summary

Step 4 has the following service spec YAML for RGW deployment:

```
service_type: rgw
service_id: REALM.ZONE
placement:
 hosts:
  - ses-min1
  - ses-min2
  - ses-min3
spec:
 realm: REALM_NAME
 zone: ZONE_NAME
```

This YAML is wrong. The correct YAML is:

```
service_type: rgw
service_id: REALM_NAME.ZONE_NAME
placement:
 hosts:
  - ses-min1
  - ses-min2
  - ses-min3
```
