### ISSUE TITLE
[doc] 6.5.3.1  Deploy Ceph Monitors and Ceph Managers

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#439]
### Type of report
   - [ ] bug
   - [X] feature request

### Source Document
6.5.3.1  Deploy Ceph Monitors and Ceph Managers:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-mon

### Summary

Would be great to know if I need to add another one if it is enough to add it into the yaml. That is not mentioned here

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-mon
susedoc.github.io

the solution is to change

```yaml
service_type: mon
placement:
  hosts:
  - host1
  - host2
```

to

```yaml
service_type: mon
placement:
  hosts:
  - host1
  - host2
  - host3
```

### Actual Results

`ceph orch apply mon host3` actually deployed a MON on one node but removed some others
