### ISSUE TITLE
[doc] 6.5.3  Deploying Services to Nodes

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#441]
### Type of report
   - [ ] bug
   - [X] feature request

### Source Document
6.5.3  Deploying Services to Nodes:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-services

### Summary

Need New chapter: Deploy Monitoring Stack

See also: https://docs.ceph.com/docs/master/cephadm/monitoring/

Users need to run

```
ceph mgr module enable prometheus
```

and then apply something like

```yaml
service_type: prometheus
placement:
  hosts:
  - hostname
---
service_type: node-exporter
---
service_type: alertmanager
placement:
  hosts:
  - hostname
---
service_type: grafana
placement:
  hosts:
  - hostname
```
