### ISSUE TITLE
[doc] 6.5.3.5  Deploy NFS Ganesha

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#443]
yaml indentation is wrong

```yaml
service_type: nfs
service_id: EXAMPLE_NFS
placement:
  hosts:
  - ses-min1
  - ses-min2
spec:
  pool: EXAMPLE_POOL
  namespace: EXAMPLE_NAMESPACE
```
