### ISSUE TITLE
Review command outputs for double-space indentation

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#445]
Some command outputs throughout the documentation use single-space for indentation. This is wrong, and should use double-space. Review the command output(s) before publication to ensure this is correct.

**Comment by sebastian-philipp** [comment]
Also, please change the indentation of placement specs from

```yaml
service_type: prometheus
placement:
  hosts:
  - hostname
```

to the more common indentation:

```yaml
service_type: prometheus
placement:
  hosts:
    - hostname
```
