### ISSUE TITLE
[doc] 5.4.3.5  Deploy iSCSI Gateways

### ISSUE THREAD

**Issue by bk201** [SUSE/doc-ses#693]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
5.4.3.5  Deploy iSCSI Gateways:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-igw

### Summary

The `trusted_ip_list` field can't contain spaces after each comma ATM. I'l suggest removing the space between `IP_ADDRESS_1` and `IP_ADDRESS_2` in the example and state this restriction in the NOTE admonition section. 

Related:
- bsc `#1177100`
- https://github.com/ceph/ceph-iscsi/issues/219

```
service_type: iscsi
service_id: EXAMPLE_ISCSI
placement:
  hosts:
  - ses-min1
  - ses-min2
  - ses-min3
spec:
  pool: EXAMPLE_POOL
  api_user: EXAMPLE_USER
  api_password: EXAMPLE_PASSWORD
  trusted_ip_list: "IP_ADDRESS_1, IP_ADDRESS_2"   <-- to "IP_ADDRESS_1,IP_ADDRESS_2"
```
