### ISSUE TITLE
[doc] 16.1.1  Deploying using the command-line interface

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#861]
Those two sections:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#monitoring-cli-spec

and

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-monitoring

should actually be completely equal. There is no difference in deploying the monitoring stack between day 1 and day 2.

e.g Let's use the apply -i instead. As we have decided to always use the yaml representation, we should stick with it here as well.

`monitoring.yaml`:
```yaml
service_type: prometheus
placement:
  hosts:
  - ses-min2
---
service_type: node-exporter
---
service_type: alertmanager
placement:
  hosts:
  - ses-min4
---
service_type: grafana
placement:
  hosts:
  - ses-min3
```
And then
```
ceph mgr module enable prometheus
$ ceph orch apply -i monitoring.yaml
```

We should not have two different ways to deploy the monitoring stack.
