### ISSUE TITLE
[doc] 7.2  Upgrading the Salt Master - add DeepSea registry credentials option

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#952]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
7.2  Upgrading the Salt Master:

https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#upgrade-salt-master

### Summary
https://github.com/SUSE/DeepSea/pull/1878 gave DeepSea v0.9.36 the ability to specify registry credentials. We need to update this section to include mention of this. Currently, it gives the following example:

```
ses7_container_image: 192.168.121.1:5000/my/ceph/image
ses7_container_registries:
  - location: 192.168.121.1:5000
```

If the user needs to specify authentication information for their registry, they need to add something like the following to the above:

```
ses7_container_registry_auth:
  registry: 192.168.121.1:5000
  username: my_username_here
  password: my_very_secure_password_here
```
