### ISSUE TITLE
[doc] 16.7.2  Configuring the Prometheus Alertmanager for SNMP

### ISSUE THREAD

**Issue by votdev** [SUSE/doc-ses#986]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
16.7.2  Configuring the Prometheus Alertmanager for SNMP:

https://documentation.suse.com/ses/7/single-html/ses-admin/#configure-prometheus-alertmanager-for-snmp

### Summary

The example spec file is incorrect.

### Steps To Reproduce

n/a

### Expected Results

The spec file should look like:
```
  service_type: alertmanager
  placement:
    hosts:
    - HOSTNAME
  user_data:
    default_webhook_urls:
    - 'http://IP_OR_FQDN:9099/'
```

### Actual Results

```
master:~ # cat  /tmp/cephadm-apply.yml
service_type: alertmanager
service_id: testing_am
placement:
  hosts:
  - master
webhook_configs:
- 'https://foo:8443/'
EOF
master:~ # ceph orch apply -i /tmp/cephadm-apply.yml
Error EINVAL: ServiceSpec: __init__() got an unexpected keyword argument 'webhook_configs'
```

### Notes

n/a
